#!/bin/bash
# Thin wrapper around the qo100sdl binary for use as the systemd ExecStart -
# reads the saved display resolution choice from settings.json fresh on
# every launch and sets QO100_DISPLAY accordingly, so switching resolution
# from the SET page (save + restart) picks it up automatically without the
# app needing to touch its own systemd unit.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETTINGS_FILE="$SCRIPT_DIR/settings.json"

# An already-set QO100_DISPLAY (e.g. from a systemd unit generated by
# `setup_autostart.sh WxH` for a genuinely different physical panel) wins -
# settings.json is only the fallback for the common case of no override.
if [ -z "$QO100_DISPLAY" ]; then
    RESOLUTION="1024x600"
    if [ -f "$SETTINGS_FILE" ]; then
        IS_800x480="$(python3 -c "
import json, sys
try:
    with open('$SETTINGS_FILE') as f:
        settings = json.load(f)
    print('1' if settings.get('display_800x480') else '0')
except Exception:
    print('0')
")"
        if [ "$IS_800x480" = "1" ]; then
            RESOLUTION="800x480"
        fi
    fi
    export QO100_DISPLAY="$RESOLUTION"
fi

exec "$SCRIPT_DIR/build/qo100sdl"
