#!/bin/bash
# Thin wrapper around the qo100sdl binary for use as the systemd ExecStart.
#
# The display resolution chosen on the SET page is read by the app itself
# from settings.json on every launch (see resolve_display_config() in
# main.cpp), so switching resolution (save + restart) needs nothing here.
# This script used to turn a saved 800x480 choice into QO100_DISPLAY, but
# that pinned the "real" screen size to 800x480 as well, which greyed out
# every larger choice on SET even on a larger panel.
#
# An already-set QO100_DISPLAY (e.g. from a systemd unit generated by
# `setup_autostart.sh WxH` for a genuinely different physical panel) is
# passed through unchanged and still wins.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

exec "$SCRIPT_DIR/build/qo100sdl"
